# ***Matrix computation with NumPy***

Matrix is implemented as a simple 2D array in Numpy. However, it behaves very differently from 1D array in Numpy.

### **Required reading**

Carefully study [NumPy: the absolute basics of beginners](https://numpy.org/doc/stable/user/absolute_beginners.html). 

*** Practice, Practice, Practice!!!  If you do not practice, even if exams, quizzes, and homework are all open book, you will have great difficulty to figure out what is going on.  All the materials from now on will build upon the basics covered in the last and this weeks.


---

Below is the notebook used in the lecture videos. Summary is in the lecture note. This notebook is provided just for your practice.

In [2]:
import numpy as np
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
m = [[1,2],[3,4],[5,6]]
m

[[1, 2], [3, 4], [5, 6]]

In [6]:
k = data[1,0]
k

3

In [13]:
b = data[:,[1]]
b

array([[2],
       [4],
       [6]])

In [20]:
d = data[[0,1], [[0]]]
d

array([[1, 3]])

In [21]:
e = data[[1,2,0], [1,0,1]]
e

array([4, 5, 2])

In [22]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
y = x[    [[0,1]]   , [1,2]  ]
y

array([[1, 5]])

In [24]:
z = x[  [ [1],[2] ], [1,0]  ]
z

array([[4, 3],
       [7, 6]])

In [30]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
x.ndim

2

In [32]:
x.shape

(4, 3)

In [33]:
x.size

12

In [34]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [35]:
unique_rows = np.unique(a_2d, axis=0)
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_counts=True, return_index=True)
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
indices

array([0, 1, 2])

In [40]:
occurrence_count

array([2, 1, 1])

In [43]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [44]:
b = np.expand_dims(a, axis = 0)
b

array([[1, 2, 3]])

In [45]:
b = a[np.newaxis,:]
b

array([[1, 2, 3]])

In [46]:
b = np.expand_dims(a, axis = 1)
b

array([[1],
       [2],
       [3]])

In [47]:
b = a[:,np.newaxis]
b

array([[1],
       [2],
       [3]])

In [48]:
c = np.squeeze(b)
c

array([1, 2, 3])

In [52]:
d = np.flip(c)
d

array([3, 2, 1])

In [54]:
e = np.sort(d)
e

array([1, 2, 3])

In [55]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
y = x
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
y = y[[0,3]]

In [59]:
y

array([[ 0,  1,  2],
       [ 9, 10, 11]])

In [60]:
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])
print(a1)
print(a2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [62]:
b = np.hstack((a1,a2))
b

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [64]:
x = np.arange(1,25).reshape(4,6)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [67]:
y = np.squeeze(x.reshape(1,24))
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [68]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
a,b,c = np.hsplit(x,3)
print(a)
print(b)
print(c)

[[ 1  2  3  4]
 [13 14 15 16]]
[[ 5  6  7  8]
 [17 18 19 20]]
[[ 9 10 11 12]
 [21 22 23 24]]


In [71]:
d,e = np.vsplit(x,2)
print(d)
print(e)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[13 14 15 16 17 18 19 20 21 22 23 24]]


In [75]:
x.max(axis=1)

array([12, 24])