# ***Matrix computation with NumPy***

Matrix is implemented as a simple 2D array in Numpy. However, it behaves very differently from 1D array in Numpy.

### **Required reading**

Carefully study [NumPy: the absolute basics of beginners](https://numpy.org/doc/stable/user/absolute_beginners.html). (Most content on this page will be covered in the course.)  Although not required, it is strongly recommended that you memorize most of this tutorial. This way, you will understand how the data is manipulated in NumPy. <br> &nbsp;&nbsp;&nbsp;&nbsp; (Note: It is not easy to remember *all* NumPy functions. However, you need to know where to find the *syntaxes, functions,* or *operators* of NumPy when you need them. Don't be scared of *googling* and using *stackoverflow.com*.)

*** Practice, Practice, Practice!!!  If you do not practice, even if exams, quizzes, and homework are all open book, you will have great difficulty to figure out what is going on.  All the materials from now on will build upon the basics covered in the last and this weeks.


---

Below is the notebook used in the lecture videos. Summary is in the lecture note. This notebook is provided just for your practice.

In [ ]:
import numpy as np
x = np.arange(1,25).reshape(2,12)
x

In [ ]:
y = np.arange(1,7).reshape(3,2)
y

In [ ]:
z = y.T
z

In [ ]:
k = y @ z
k

In [ ]:
x_test = np.arange(30).reshape(3, 2, 5)

x_test

In [ ]:
y = np.transpose(x_test, (0, 2, 1))
y

In [47]:
data = np.arange(1,7).reshape(2,3)
data

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
b = np.flip(data)
b

array([[6, 5, 4],
       [3, 2, 1]])

In [49]:
data = np.arange(1,7).reshape(2,3)
c = np.flip(data, axis = 1)
c

array([[3, 2, 1],
       [6, 5, 4]])

In [50]:
data = np.arange(1,7).reshape(2,3)
data[1] = np.flip(data[1])
data

array([[1, 2, 3],
       [6, 5, 4]])

In [51]:
data = np.arange(1,7).reshape(2,3)
data[:,1] = np.flip(data[:,1])
data

array([[1, 5, 3],
       [4, 2, 6]])

In [52]:
data = np.arange(1,7).reshape(2,3)
d = np.tile(data, (3,1))
d

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
data = np.arange(1,7).reshape(2,3)
e = np.tile(data.reshape(6,1), (1,3))
e

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [58]:
a = np.random.normal(size=(6,6))
a

array([[ 0.95106162,  1.34173375, -0.5028821 ,  1.54876266, -1.83820616,
         0.7447294 ],
       [ 0.78658831,  1.4944532 , -0.055797  ,  0.06391199, -0.63868097,
        -1.33131469],
       [-0.04167275,  0.49212683, -0.08982189, -1.40767435,  1.1936329 ,
         1.80788788],
       [-1.4307225 ,  1.48644386,  0.65758837,  1.09162746, -0.6125229 ,
         0.304666  ],
       [ 0.12811104, -0.72063968, -1.45000448,  0.23870237,  2.03664282,
        -0.23030733],
       [-0.56973166, -0.26882612,  0.88384734, -0.99498714, -0.29454149,
         0.3055197 ]])